#!/usr/bin/env bash
# Written by: predatorfreak

# Environment checks.
if [ ! `whoami` = "root" ]; then
	echo "ERROR: Blackhole requires root privilages to modify iptables rules."
	exit 1
fi

if [ -f /etc/blackhole/blackhole.conf ]; then
	. /etc/blackhole/blackhole.conf
	export CONFDIR="/etc/blackhole"
elif [ -f $PWD/config/blackhole.conf ]; then
	. "$PWD"/config/blackhole.conf
	export CONFDIR="$PWD/config"
else
	echo "ERROR: Couldn't find configuration file, dieing."
	exit 1
fi

if [ -d "$PREFIX"/share/blackhole/modules -a -f "$PREFIX"/share/blackhole/modules/core.bmod ] \
	&& [ ! -f "$PWD"/.bhdev ]; then
	export MODDIR="$PREFIX/share/blackhole/modules"
elif [ -d "$PWD"/modules -a -f "$PWD"/modules/core.bmod ]; then
	export MODDIR="$PWD/modules"
else
	echo "ERROR: Modules directory doesn't exist, dieing."
	exit 1
fi

if [ -f "$PREFIX"/share/blackhole/includes/module-functions -a -f "$PREFIX"/share/blackhole/includes/functions ] \
	&& [ ! -f "$PWD"/.bhdev ]; then
	. "$PREFIX"/share/blackhole/includes/module-functions
	. "$PREFIX"/share/blackhole/includes/functions
	export INCDIR=""$PREFIX"/share/blackhole/includes/"
elif [ -f "$PWD"/includes/module-functions -a -f "$PWD"/includes/functions ]; then
	. "$PWD"/includes/module-functions
	. "$PWD"/includes/functions
	export INCDIR="$PWD/includes"
else
	echo "ERROR: Couldn't find the requried includes, dieing."
	exit 1
fi

alias iptables="failcheck iptables"

case "$1" in
start)
	if [ $LOG_DROPPED_PACKETS = "YES" ]; then
		iptables -N LOG_DROP
		iptables -A LOG_DROP -j LOG --log-tcp-options --log-ip-options --log-prefix $LOGPREFIX
		iptables -A LOG_DROP -j DROP
		export DROP=LOG_DROP
	else
		export DROP=DROP
	fi

	if [ -n "${MODULES[*]}" ]; then
		MODULES=("$MODULES[@]" "core")
		echo "Setting iptables rules."
		echo -n "Loading blackhole modules: "
		for i in ${MODULES[@]}; do
		 load_module $i
		 LOADEDMODULES="$LOADEDMODULES $i"
		done
		echo
	fi
;;
stop)
	tc qdisc del dev $EXTIF handle 1:0 root 2>/dev/null > /dev/null
	tc qdisc del dev imq0 handle 1:0 root 2>/dev/null > /dev/null
	ip link set imq0 down 2> /dev/null > /dev/null
	rmmod imq 2> /dev/null > /dev/null
	iptables -F
	iptables -t nat -F
	iptables -t mangle -F
	iptables -P INPUT ACCEPT
	iptables -P FORWARD ACCEPT
	iptables -P OUTPUT ACCEPT
	iptables -X
	iptables -t nat -X
	iptables -t mangle -X
	iptables -Z
;;
restart)
	$0 stop
	sleep 2
	$0 start
;;
*)
	echo "usage: $0 [start|stop|restart]"
;;
esac
