#!/bin/sh
# installer
# Written by: predatorfreak
if [ ! `whoami` = "root" ]; then
 echo "You must be root in order to install blackhole."
 exit 1
fi

if [ -f $PWD/config/installation.conf ] && [ -f $PWD/config/blackhole.conf ]; then
 if [ -f $PWD/includes/installation-functions ]; then
  . $PWD/config/installation.conf
  . $PWD/config/blackhole.conf
  . $PWD/includes/installation-functions
 else
  echo "Unable to load the required functions."
  exit 1
 fi
else
 echo "Unable to load the configuration file."
 exit 1
fi

case "$1" in
slackware)
if [ ! -d /etc/blackhole ]; then
 echo "Beginning slackware installation."
 if [ $RCINS = "ON" ]; then
  echo "Installing init scripts..."
  rcins slackware
 else
  echo "Skipping."
 fi
 if [ $BASE = "ON" ]; then
  echo "Installing base.."
  createdirs
  cp config/{blackhole.conf,state.conf} /etc/blackhole/
  cp includes/{module-functions,functions} $PREFIX/share/blackhole/includes/
  cp modules/* $PREFIX/share/blackhole/modules/
  cp blackhole $PREFIX/bin/blackhole
  chmod +x $PREFIX/bin/blackhole
 else
  echo "Aborting installation."
  exit 1
 fi
 applyrules
 echo "Done."
 exit 0
else
 echo "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
 exit 1
fi
;;
gentoo)
if [ ! -d /etc/blackhole ]; then
 echo "Beginning gentoo installation"
 if [ $BASE = "ON" ]; then
  echo "Installing base.."
  createdirs linux
  cp config/{blackhole.conf,state.conf} /etc/blackhole/
  cp includes/{module-functions,functions} $PREFIX/share/blackhole/includes/
  cp modules/* $PREFIX/share/blackhole/modules/
  cp blackhole $PREFIX/bin/blackhole
  chmod +x $PREFIX/bin/blackhole
 else
  echo "Aborting installation."
  exit 1
 fi
 applyrules
 echo "Done."
 exit 0
else
 echo "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
 exit 1
fi
;;
fedora)
if [ ! -d /etc/blackhole ]; then
 echo "Beginning fedora installation"
 if [ $BASE = "ON" ]; then
  echo "Installing base.."
  createdirs
  cp config/{blackhole.conf,state.conf} /etc/blackhole/
  cp includes/{module-functions,functions} $PREFIX/share/blackhole/includes/
  cp modules/* $PREFIX/share/blackhole/modules/
  cp blackhole $PREFIX/bin/blackhole
  chmod +x $PREFIX/bin/blackhole
 else
  echo "Aborting installation."
  exit 1
 fi
 applyrules
 echo "Done."
 exit 0
else
 echo "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
 exit 1
fi
;;
mandriva)
if [ ! -d /etc/blackhole ]; then
 echo "Beginning mandriva installation"
 if [ $BASE = "ON" ]; then
  echo "Installing base.."
  createdirs
  cp config/{blackhole.conf,state.conf} /etc/blackhole/
  cp includes/{module-functions,functions} $PREFIX/share/blackhole/includes/
  cp modules/* $PREFIX/share/blackhole/modules/
  cp blackhole $PREFIX/bin/blackhole
  chmod +x $PREFIX/bin/blackhole
 else
  echo "Aborting installation."
  exit 1
 fi
 applyrules
 echo "Done."
 exit 0
else
 echo "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
 exit 1
fi
;;
crux)
if [ ! -d /etc/blackhole ]; then
 echo "Beginning slackware installation"
 if [ $RCINS = "ON" ]; then
  echo "Installing init scripts..."
  rcins crux
 else
  echo "Skipping."
 fi
 if [ $BASE = "ON" ]; then
  echo "Installing base.."
  createdirs
  cp config/{blackhole.conf,state.conf} /etc/blackhole/
  cp includes/{module-functions,functions} $PREFIX/share/blackhole/includes/
  cp modules/* $PREFIX/share/blackhole/modules/
  cp blackhole $PREFIX/bin/blackhole
  chmod +x $PREFIX/bin/blackhole
 else
  echo "Abort installation"
  exit 1
 fi
 applyrules
 echo "Done"
 exit 0
else
 echo "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
 exit 1
fi
;;
*)
echo "installer -"
echo "A streamlined installation system for blackhole"
echo
echo "Usage: ./installer [OPTION]"
echo
echo "Options:"
echo "slackware"
echo "gentoo"
echo "fedora"
echo "mandriva"
echo "crux"
exit 0
;;
esac
