#!/bin/bash
# installer
# Written by: predatorfreak

if [ ! `whoami` = "root" ]; then
	echo "ERROR: You must be root in order to install blackhole."
	exit 1
fi

if [ -f $PWD/config/installation.conf -a -f $PWD/config/blackhole.conf ]; then
	if [ -f $PWD/includes/installation-functions -a -f $PWD/includes/functions ]; then
		. $PWD/config/blackhole.conf
		. $PWD/config/installation.conf
		. $PWD/includes/installation-functions
		. $PWD/includes/functions
	else
		echo "ERROR: Unable to load the required functions."
		exit 1
	fi
else
	echo "ERROR: Unable to load the configuration file."
	exit 1
fi

case "$1" in
crux)
	if [ ! -d $DESTDIR/etc/blackhole ]; then
		echo "Beginning Blackhole installation."
		createdirs
		rcins crux
		cp config/{blackhole,extopts,ipblock-{input,output},qos}.conf $DESTDIR/etc/blackhole/
		cp includes/{module-functions,functions,qos-functions} $PREFIX/share/blackhole/includes/
		cp modules/* $PREFIX/share/blackhole/modules/
		cp blackhole $PREFIX/bin/blackhole
		chmod +x $PREFIX/bin/blackhole
		applyrules
		echo "Done."
		exit 0
	else
		die "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
	fi
;;
slackware)
	if [ ! -d $DESTDIR/etc/blackhole ]; then
		echo "Beggining Blackhole installation"
		createdirs
		rcins slackware
		cp config/{blackhole,extopts,ipblock-{input,output},qos}.conf $DESTDIR/etc/blackhole/
		cp includes/{module-functions,functions,qos-functions} $PREFIX/share/blackhole/includes/
		cp modules/* $PREFIX/share/blackhole/modules/
		cp blackhole $PREFIX/bin/blackhole
		chmod +x $PREFIX/bin/blackhole
		applyrules
		echo "Done."
		exit 0
	else
		die "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
	fi
;;
generic)
	if [ ! -d $DESTDIR/etc/blackhole ]; then
		echo "Beginning Blackhole installation"
		createdirs
		cp config/{blackhole,extopts,ipblock-{input,output},qos}.conf $DESTDIR/etc/blackhole/
		cp includes/{module-functions,functions,qos-functions} $PREFIX/share/blackhole/includes/
		cp modules/* $PREFIX/share/blackhole/modules/
		cp blackhole $PREFIX/bin/blackhole
		chmod +x $PREFIX/bin/blackhole
		applyrules
		echo "Done."
		exit 0
	else
		die "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
	fi
;;
*)
	echo "installer -"
	echo "A streamlined installation system for blackhole"
	echo
	echo "Usage: ./installer [OPTION]"
	echo
	echo "Options:"
	echo "crux"
	echo "slackware"
	echo "generic"
	exit 0
;;
esac
