#!/bin/bash
# upgrader
# Written by: predatorfreak

if [ ! `whoami` = "root" ]; then
	echo "You must be root in order to upgrade blackhole."
	exit 1
fi

if [ -f $PWD/config/installation.conf ]; then
	if [ -f $PWD/includes/installation-functions -a -f $PWD/includes/functions ]; then
		. $PWD/config/blackhole.conf
		. $PWD/config/installation.conf
		. $PWD/includes/installation-functions
		. $PWD/includes/functions
	else
		echo "Unable to load the required functions."
		exit 1
	fi
else
	echo "Unable to load the configuration file."
	exit 1
fi

case "$1" in
crux)
	if [ -d $DESTDIR/etc/blackhole ]; then
		echo "Upgrading Blackhole installation"
		createdirs
		rcins crux
		cp -i config/{blackhole,extopts,ipblock-{input,output},qos}.conf /etc/blackhole/
		cp includes/{module-functions,functions,qos-functions} $PREFIX/share/blackhole/includes/
		cp modules/* $PREFIX/share/blackhole/modules/
		cp blackhole $PREFIX/bin/blackhole
		chmod +x $PREFIX/bin/blackhole
		applyrules
		echo "Done."
		exit 0
	else
		die "Upgrader: The directory /etc/blackhole doesn't exist, please run installer instead."
	fi
;;
slackware)
	if [ -d $DESTDIR/etc/blackhole ]; then
		echo "Upgrading Blackhole installation"
		createdirs
		rcins slackware
		cp -i config/{blackhole,extopts,ipblock-{input,output},qos}.conf /etc/blackhole/
		cp includes/{module-functions,functions,qos-functions} $PREFIX/share/blackhole/includes/
		cp modules/* $PREFIX/share/blackhole/modules/
		cp blackhole $PREFIX/bin/blackhole
		chmod +x $PREFIX/bin/blackhole
		applyrules
		echo "Done."
		exit 0
	else
		die "Upgrader: The directory /etc/blackhole doesn't exist, please run installer instead."
	fi
;;
generic)
	if [ -d $DESTDIR/etc/blackhole ]; then
		echo "Upgrading Blackhole installation"
		createdirs
		cp -i config/{blackhole,extopts,ipblock-{input,output},qos}.conf /etc/blackhole/
		cp includes/{module-functions,functions,qos-functions} $PREFIX/share/blackhole/includes/
		cp modules/* $PREFIX/share/blackhole/modules/
		cp blackhole $PREFIX/bin/blackhole
		chmod +x $PREFIX/bin/blackhole
		applyrules
		echo "Done."
		exit 0
	else
		die "Upgrader: The directory /etc/blackhole doesn't exist, please run installer instead."
	fi
;;
*)
	echo "upgrader -"
	echo "A streamlined upgrade system for blackhole"
	echo
	echo "Usage: ./upgrader [OPTION]"
	echo
	echo "Options:"
	echo "crux"
	echo "slackware"
	echo "generic"
	exit 0
;;
esac
